DemoPetShop/Models/AnimalModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoPetShop.Models
{
    public class AnimalModel
    {
        public string Id { get; set; }
        public string NickName { get; set; }
        public string Species { get; set; }
        public int Age { get; set; }
    }
}

DemoPetShop/Models/ErrorViewModel.cs
using System;

namespace DemoPetShop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty( RequestId );
    }
}

DemoPetShop/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DemoPetShop.Domain.Entity;
using DemoPetShop.Models;
using DemoPetShop.Services.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace DemoPetShop.Controllers
{
    public class AnimalController : Controller
    {
        private readonly IAnimalService m_AnimalService;
        public AnimalController( IAnimalService p_AnimalService )
        {
            m_AnimalService = p_AnimalService;
        }

        public IActionResult Index( )
        {
            List<Animal> animals =  m_AnimalService.ListAll( );

            List<AnimalModel> animalModels = new List<AnimalModel>( );

            foreach ( Animal animal in animals )
            {
                animalModels.Add( new AnimalModel( )
                {
                    Id = animal.Id,
                    NickName = animal.NickName,
                    Age = animal.Age,
                    Species = animal.Species
                });
            }

            ViewBag.Animals = animalModels;

            return View( );
        }

        public IActionResult Detail( string id )
        {
            Animal animal = m_AnimalService.GetById( id );

            AnimalModel animalModel = new AnimalModel( )
            {
                Id = animal.Id,
                NickName = animal.NickName,
                Age = animal.Age,
                Species = animal.Species
            };

            ViewBag.Animal = animalModel;
            return View( );
        }

        public IActionResult Insert(  )
        {
            return View( );
        }

        public IActionResult Create( AnimalModel animalModel )
        {
            Animal animal = new Animal( )
            {
                NickName = animalModel.NickName,
                Age = animalModel.Age,
                Species = animalModel.Species
            };

            m_AnimalService.Insert( animal );

            return RedirectToAction( "Index" );
        }

        public IActionResult Delete( string id )
        {
            m_AnimalService.Delete( id );
            return RedirectToAction( "Index" );
        }
    }
}

DemoPetShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoPetShop.Models;

namespace DemoPetShop.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index( )
        {
            return View( );
        }

        public IActionResult Privacy( )
        {
            return View( );
        }

        [ResponseCache( Duration = 0, Location = ResponseCacheLocation.None, NoStore = true )]
        public IActionResult Error( )
        {
            return View( new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier } );
        }
    }
}

DemoPetShop/Views/Animal/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
    AnimalModel animalModel = ViewBag.Animal;
}

<h1>Detail</h1>

<hr />
<div>@animalModel.Id</div>
<div>@animalModel.NickName</div>
<div>@animalModel.Age</div>
<div>@animalModel.Species</div>

<hr />
@Html.ActionLink( "List Animals", "Index", "Animal" )

DemoPetShop/Views/Animal/Index.cshtml
@{
    
    ViewData["Title"] = "Animal List";
}

<h1>Animals</h1>
@Html.ActionLink( "Add", "Insert", "Animal" )

<table>
    <thead>
        <tr>
            <td>Id</td>
            <td>NickName</td>
            <td>Age</td>
            <td>Species</td>
        </tr>
    </thead>
    <tbody>
        @{
            List<AnimalModel> animals = ViewBag.Animals;
            foreach ( AnimalModel item in animals )
            {
                <tr>
                    <td>@Html.ActionLink( @item.Id.ToString( ), "Detail", "Animal", new { @id = item.Id } )</td>
                    <td>@item.NickName</td>
                    <td>@item.Age</td>
                    <td>@item.Species</td>
                    <td>@Html.ActionLink( "Delete", "Delete", "Animal", new { @id = item.Id } )</td>
                </tr>
            }
        }
    </tbody>
</table>

DemoPetShop/Views/Animal/Insert.cshtml
@{
    ViewData["Title"] = "Insert";
}

<h1>Insert</h1>


<form method="post" action="@Url.Action("Create", "Animal")">
    <label>NickName</label>
    <input id="NickName" name="NickName" type="text" />
    <label>Species</label>
    <input id="Species" name="Species" type="text" />
    <label>Age</label>
    <input id="Age" name="Age" type="text" />
    <input type="submit" />
</form>

DemoPetShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoPetShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoPetShop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoPetShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Index">Animal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - DemoPetShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>